-- MySQL Script generated by MySQL Workbench
-- lun 3 mag 2021, 16:13:46
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema rendezvous
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rendezvous
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rendezvous-roomrouter` ;
USE `rendezvous-roomrouter` ;

-- -----------------------------------------------------
-- Table `rendezvous`.`room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rendezvous-roomrouter`.`room` (
  `id` VARCHAR(255) NOT NULL,
  `name` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rendezvous`.`chatroom`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rendezvous-roomrouter`.`chatroom` (
  `id` VARCHAR(255) NOT NULL,
  `serverurl` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rendezvous`.`videoroom`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rendezvous-roomrouter`.`videoroom` (
  `id` VARCHAR(255) NOT NULL,
  `serverurl` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rendezvous`.`user_has_room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rendezvous-roomrouter`.`user_has_room` (
  `user_id` VARCHAR(255) NOT NULL,
  `room_id` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`user_id`, `room_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rendezvous`.`room_has_videoroom`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rendezvous-roomrouter`.`room_has_videoroom` (
  `room_id` VARCHAR(255) NOT NULL,
  `videoroom_id` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`room_id`, `videoroom_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rendezvous`.`room_has_chatroom`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rendezvous-roomrouter`.`room_has_chatroom` (
  `room_id` VARCHAR(255) NOT NULL,
  `chatroom_id` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`room_id`, `chatroom_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
